# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [1]:
# The code goes here
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [8]:
#Code comes here
arr1 = np.tile(1,10)
print(arr1)
arr2 = np.arange(0,21,1, dtype="int")
print(arr2)
arr3 = np.ones((1,5,5))
print(arr3)
#OR OTHER WAY:
print(np.ones(10))
print(np.array(range(21)))
print(np.ones((5, 5), dtype=int))


[1 1 1 1 1 1 1 1 1 1]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [2]:
# Code comes here
arr2 = np.random.rand(3, 3, 3)
print(arr2)

arr3 = np.random.rand(27,)
print(arr3)

[[[0.44909783 0.0857903  0.66046259]
  [0.79311493 0.17834812 0.36276768]
  [0.75152472 0.63104199 0.59315886]]

 [[0.03596454 0.71216161 0.64884334]
  [0.5372875  0.37423376 0.70427692]
  [0.44441604 0.01252221 0.90742204]]

 [[0.79993677 0.14249007 0.3652703 ]
  [0.81615616 0.70838386 0.53914593]
  [0.09101564 0.35789399 0.42224106]]]
[0.20898058 0.1713259  0.41118639 0.34212029 0.2783816  0.26824784
 0.46891848 0.52070801 0.52317972 0.28326244 0.28584481 0.32713284
 0.20652109 0.88563105 0.77709503 0.85858098 0.37636726 0.22764676
 0.24932806 0.42126809 0.58291223 0.70282844 0.35420788 0.16855701
 0.40753845 0.30433735 0.5824361 ]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [3]:
# Code comes he
arr4 = np.linspace(1, 10, 20)
print(arr4)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [5]:
import numpy as np
a = np.arange(1, 17).reshape(4,-1)

In [ ]:
20

In [28]:
#Code goes here
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [15]:
# Code come here
array = np.array([6, 7, 8, 9, 10])
array

array([ 6,  7,  8,  9, 10])

```python
array([ 6,  7,  8,  9, 10])
```

In [ ]:
# Code comes here

## 2.5 

Calculate the sum of all the numbers in `a`.

In [7]:
# Code comes here
sum(a)

array([28, 32, 36, 40])

## 2.6 

Calculate the sum of each row in `a`.

In [6]:
# Code comes here
a.sum(axis=1)

array([10, 26, 42, 58])

## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [ ]:
# Code comes here

# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [ ]:
# Codes comes here

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [ ]:
# Code comes here

## 2.10 

How many rows and columns are there in the dataframe?

In [ ]:
#Code comes here

## 2.11

What is the mean `co2_emission` of the whole dataset?

In [ ]:
# Code comes here

## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [ ]:
# Code comes here

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [ ]:
#code comes here

## 2.14

Which country consumes the least amount of beef per person per year?


In [ ]:
# code comes here

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [ ]:
# code comes here

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [ ]:
# code comes here

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.